### ISSUE TITLE
Failed to download the model files

### ISSUE THREAD

**Issue by davidmrau** [monilouise/deep-learning#1]
The models seem not to be available on git lfs anymore. Could you re-upload them or send me a google drive link? Thanks a lot!

**Comment by LeoPapais** [comment]
Hi there!

Can you check this issue, @monilouise  ?

Thanks in advance!

**Comment by monilouise** [comment]
Hi,

The models are available on https://drive.google.com/drive/folders/1X493GGu02QIRWfs6nmPYgCFyEBZ2CX7c

But in fact, I intend to retrain them in the library's most recent version.

**Comment by monilouise** [comment]
(message above)
